#!/bin/bash

mkdir -p inputs

DIR=$(pwd -P)

cd cpp-new/pbbsbench/testData/graphData \
&& make -j rMatGraph edgeArrayToAdj \
&& ./rMatGraph 10000000 rmat-10M-edgearray \
&& ./edgeArrayToAdj -o $DIR/inputs/rmat-10M-symm rmat-10M-edgearray \
&& rm -f rmat-10M-edgearray

cd $DIR
make -C ml graphio.default.old-mlton.bin
ml/bin/graphio.default.old-mlton.bin inputs/rmat-10M-symm -outfile inputs/rmat-10M-symm-bin

cd cpp-new/pbbsbench/testData/geometryData \
&& make randPoints \
&& ./randPoints -s 20000000 $DIR/inputs/uniform-circle-20M

cd $DIR/inputs
cat sources.txt sources.txt sources.txt sources.txt > sources4.txt
