#!/bin/bash

ROOT=$(git rev-parse --show-toplevel)

git submodule update --init --recursive
echo "[INFO] submodules initialized"

echo "[INFO] installing mpl (may appear unresponsive but is just taking a while)"
$ROOT/scripts/install_mpls

mkdir -p figures
mkdir -p results
mkdir -p inputs

mkdir -p small/figures
mkdir -p small/results
