#!/bin/bash

ROOT=$(git rev-parse --show-toplevel)
GEN=scripts/gencmds
RUN=scripts/runcmds

NOW=$(date '+%y%m%d-%H%M%S')
mkdir -p $ROOT/results
RESULTS=$ROOT/results/$NOW

rm -f $ROOT/cpp/bin/*.bin
rm -f $ROOT/ml/bin/*.bin

# all of the extra arguments get sent to scripts/runcmds.py with $@ below
( \
  $GEN $ROOT/ml-exp.json; \
  $GEN $ROOT/cpp-exp.json \
) | $RUN --repeat 1 --compile --output $RESULTS $@

( \
  $GEN $ROOT/ml-space-exp.json; \
  $GEN $ROOT/cpp-space-exp.json \
) | $RUN --repeat 10 --compile --output $RESULTS $@

echo "[INFO] wrote results to $RESULTS"
