#!/bin/bash

ROOT=$(git rev-parse --show-toplevel)
GEN=scripts/gencmds
RUN=scripts/runcmds

NOW=$(date '+%y%m%d-%H%M%S')
mkdir -p $ROOT/small/results
RESULTS=$ROOT/small/results/$NOW

rm -f $ROOT/cpp-new/bin/*.bin
rm -f $ROOT/ml/bin/*.bin

PROCLIST=1,4,8

( \
  $GEN --procs $PROCLIST $ROOT/small/ml-exp.json; \
  $GEN --procs $PROCLIST $ROOT/small/cpp-exp.json \
) | $RUN --repeat 1 --compile --output $RESULTS

echo "[INFO] wrote results to $RESULTS"
