#!/bin/bash

ROOT=$(git rev-parse --show-toplevel)
GEN=scripts/gencmds
RUN=scripts/runcmds

NOW=$(date '+%y%m%d-%H%M%S')
mkdir -p $ROOT/small/results
RESULTS=$ROOT/small/results/$NOW

rm -f $ROOT/cpp-new/bin/*.bin
rm -f $ROOT/ml/bin/*.bin

# all of the extra arguments get sent to scripts/runcmds.py with $@ below
( \
  $GEN $ROOT/small/ml-exp.json; \
  $GEN $ROOT/small/cpp-exp.json \
) | $RUN --repeat 1 --compile --output $RESULTS $@

echo "[INFO] wrote results to $RESULTS"
